apiVersion: apps/v1
kind: Deployment
metadata:
  name: kcl-operator-webhook
  labels:
    app: kcl-operator-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kcl-operator-webhook
  template:
    metadata:
      labels:
        app: kcl-operator-webhook
    spec:
      containers:
        - name: kcl-operator-webhook
          image: kcllang/webhookserver
          imagePullPolicy: Always
          args:
            - -tls-cert-file=/etc/webhook/certs/cert.pem
            - -tls-key-file=/etc/webhook/certs/key.pem
            - -addr=:8081
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: kcl-operator-webhook-certs
---
apiVersion: v1
kind: Service
metadata:
  name: kcl-operator-webhook
  labels:
    app: kcl-operator-webhook
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8081
  selector:
    app: kcl-operator-webhook
