apiVersion: apps/v1
kind: Deployment
metadata:
  name: kcl-webhook-server
  labels:
    app: kcl-webhook-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kcl-webhook-server
  template:
    metadata:
      labels:
        app: kcl-webhook-server
    spec:
      serviceAccountName: kcl-webhook
      initContainers:
        - name: kcl-webhook-init
          image: kcllang/webhook-init
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /etc/webhook/certs
              name: webhook-certs
          env:
            - name: MUTATE_CONFIG
              value: kcl-webhook-server
            - name: WEBHOOK_SERVICE
              value: kcl-webhook-server
            - name: WEBHOOK_NAMESPACE
              value: default
      containers:
        - name: kcl-webhook-server
          image: kcllang/webhook-server
          imagePullPolicy: Always
          args:
            - -tls-cert-file=/etc/webhook/certs/tls.crt
            - -tls-key-file=/etc/webhook/certs/tls.key
            - -addr=:8081
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kcl-webhook-server
  labels:
    app: kcl-webhook-server
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8081
  selector:
    app: kcl-webhook-server
